# Generated by Django 4.2.6 on 2024-01-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Junction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Owner_name", models.CharField(max_length=20)),
                ("Owner_phone", models.IntegerField(max_length=15)),
                ("Owner_address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Number", models.CharField(max_length=10)),
                ("Color", models.CharField(max_length=10)),
                ("Producer", models.CharField(max_length=10)),
                ("Type", models.CharField(max_length=10)),
                ("Year", models.IntegerField(max_length=4)),
                (
                    "Owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="traffic_management.owner",
                    ),
                ),
            ],
        ),
    ]
