# Generated by Django 4.2.6 on 2024-01-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="Owner_phone",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="Year",
            field=models.IntegerField(),
        ),
    ]
