# Generated by Django 4.2.6 on 2024-01-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0002_alter_owner_owner_phone_alter_vehicle_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="Owner_phone",
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="Year",
            field=models.IntegerField(max_length=4),
        ),
    ]
