# Generated by Django 4.2.6 on 2024-01-27 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0004_alter_owner_owner_phone_alter_vehicle_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="junction",
            name="Name",
        ),
    ]
