# Generated by Django 4.2.6 on 2024-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0005_remove_junction_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="Owner_email",
            field=models.CharField(default="<EMAIL>", max_length=30),
        ),
    ]
