# Generated by Django 4.2.6 on 2024-01-31 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0006_owner_owner_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Number", models.CharField(max_length=10, unique=True)),
                ("Status", models.CharField(default="available", max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="Number",
            new_name="PlateNumber",
        ),
        migrations.AddField(
            model_name="junction",
            name="Light",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="owner",
            name="Owner_age",
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="owner",
            name="Owner_driver_license",
            field=models.CharField(default="0000000000", max_length=10),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="Condition",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="Speed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="Year",
            field=models.IntegerField(default=2000),
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Vehicle_PlateNumber", models.CharField(max_length=10)),
                ("Vehicle_Speed", models.IntegerField()),
                ("Date", models.DateField(auto_now_add=True)),
                ("Time", models.TimeField(auto_now_add=True)),
                (
                    "Junction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="traffic_management.junction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fine", models.IntegerField()),
                ("status", models.CharField(max_length=10)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="traffic_management.owner",
                    ),
                ),
            ],
        ),
    ]
