# Generated by Django 5.0.1 on 2024-01-31 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0006_owner_owner_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="Owner_age",
            field=models.IntegerField(
                default=99,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="owner",
            name="Owner_driver_license",
            field=models.CharField(blank=True, default="none", max_length=10),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="condition",
            field=models.IntegerField(
                default=80,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="speed",
            field=models.IntegerField(
                default=99,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="Year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1980),
                    django.core.validators.MaxValueValidator(2024),
                ]
            ),
        ),
    ]
