# Generated by Django 4.2.6 on 2024-02-01 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "traffic_management",
            "0007_plates_rename_number_vehicle_platenumber_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="Producer",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="Type",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="Year",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="VType",
            field=models.CharField(default="Year_Maker_Model", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="owner",
            name="Owner_driver_license",
            field=models.CharField(default="0000000000", max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="Color",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="PlateNumber",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="traffic_management.plates",
            ),
        ),
    ]
