# Generated by Django 5.0.1 on 2024-01-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "traffic_management",
            "0007_owner_owner_age_owner_owner_driver_license_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="platenumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
