# Generated by Django 4.2.6 on 2024-02-03 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0009_alter_log_junction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fine",
        ),
    ]
