# Generated by Django 4.2.6 on 2024-02-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0011_fine"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver_License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("License_Number", models.CharField(max_length=10)),
                ("Issue_Date", models.DateField(auto_now_add=True)),
                ("Expire_Date", models.DateField()),
                ("Status", models.CharField(default="Valid", max_length=10)),
                ("Score", models.IntegerField(default=12)),
                (
                    "Owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="traffic_management.owner",
                    ),
                ),
            ],
        ),
    ]
