# Generated by Django 4.2.6 on 2024-02-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0012_driver_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver_license",
            name="Expire_Date",
            field=models.DateField(default=None),
        ),
    ]
