# Generated by Django 4.2.6 on 2024-02-03 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0013_alter_driver_license_expire_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Driver_License",
            new_name="DriverLicense",
        ),
    ]
