# Generated by Django 4.2.6 on 2024-02-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0014_rename_driver_license_driverlicense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverlicense",
            name="Expire_Date",
            field=models.CharField(default="LifeLong"),
        ),
    ]
