# Generated by Django 4.2.6 on 2024-02-03 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0015_alter_driverlicense_expire_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DriverLicense",
        ),
    ]
