# Generated by Django 4.2.6 on 2024-02-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0017_driverlicense"),
    ]

    operations = [
        migrations.CreateModel(
            name="Traffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField(auto_now_add=True)),
                ("Driver", models.CharField(max_length=20)),
                (
                    "Owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="traffic_management.owner",
                    ),
                ),
            ],
        ),
    ]
