# Generated by Django 4.2.6 on 2024-02-03 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0019_test_delete_traffic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
