# Generated by Django 4.2.6 on 2024-02-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("traffic_management", "0020_delete_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverlicense",
            name="Owner",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="traffic_management.owner",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="PlateNumber",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="traffic_management.plates",
            ),
        ),
    ]
